FROM jenkins/jenkins:lts

USER root

# Installer Docker dans le conteneur
RUN apt-get update && apt-get install -y docker.io

# Ajouter le groupe docker avec le bon GID de ta machine (GID = 109)
RUN groupadd -g 109 docker || true

# Ajouter l'utilisateur jenkins au groupe docker
RUN usermod -aG docker jenkins

USER jenkins
