FROM jenkins/jenkins:lts

USER root

# Installer Docker dans le conteneur
RUN apt-get update && apt-get install -y docker.io

# Trouver le GID du socket Docker sur ta machine hôte (ex: 998)
# et le forcer ici dans le conteneur
RUN groupadd -g 998 docker || true

# Ajouter l’utilisateur jenkins au groupe docker
RUN usermod -aG docker jenkins

USER jenkins
