pipeline {
    agent any

    environment {
        SONARQUBE = 'SonarQube-Local'
        DOCKER_IMAGE = "skanderlaribi/achat-backend:latest"
    }

    tools {
        maven 'Maven-3.8.5'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'SkanderLARIBI-4TWIN9-groupe-5-2', url: 'https://github.com/Hmaidi-Ala-Eddine/achat-twin9-groupe-5.git'
            }
        }

        stage('Build Maven') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE}") {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }
    }

    post {
        always {
            echo 'Pipeline terminée.'
        }
    }
}
